//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentaire
    {
        public int Id { get; set; }
        public string CorpsCommentaire { get; set; }
        public Nullable<int> IdMusique { get; set; }
        public Nullable<int> Note { get; set; }
        public string NomUser { get; set; }
    
        public virtual Musique Musique { get; set; }
    }
}
