//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musique
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Style { get; set; }
        public string LienTelechargement { get; set; }
        public string LienEcoute { get; set; }
        public int IdAlbum { get; set; }
    
        public virtual Album Album { get; set; }
    }
}
